apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: emit-prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - datasourceUid: emit-tempo
          name: traceID
