apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: emit-tempo
    url: http://tempo:3200
    access: proxy
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: emit-prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToMetrics:
        datasourceUid: emit-prometheus
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags:
          - key: service.name
            value: service
        queries:
          - name: "Request rate"
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))'
          - name: "Request error rate"
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags,status_code="STATUS_CODE_ERROR"}[5m]))'
          - name: "Request duration p95"
            query: 'histogram_quantile(.95, sum(rate(traces_spanmetrics_duration_seconds_bucket{$$__tags}[5m])) by (le))'
