namespace Emit.Persistence.PostgreSQL;

using System.Text.Json;
using Emit.Models;
using Emit.Persistence.PostgreSQL.Configuration;
using Emit.Persistence.PostgreSQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.Options;

/// <summary>
/// Entity Framework Core DbContext for outbox persistence.
/// </summary>
/// <remarks>
/// <para>
/// This context manages the outbox entries and global lease tables.
/// All column names use camelCase convention by default.
/// </para>
/// <para>
/// Indexes created:
/// <list type="bullet">
/// <item><description>Unique compound index on (GroupKey, Sequence)</description></item>
/// <item><description>Composite index on (Status, GroupKey)</description></item>
/// <item><description>Index on CompletedAt for cleanup queries</description></item>
/// </list>
/// </para>
/// </remarks>
internal sealed class OutboxDbContext : DbContext
{
    private readonly PostgreSqlOptions options;

    /// <summary>
    /// Initializes a new instance of the <see cref="OutboxDbContext"/> class.
    /// </summary>
    /// <param name="dbContextOptions">The DbContext options.</param>
    /// <param name="options">The PostgreSQL options.</param>
    public OutboxDbContext(
        DbContextOptions<OutboxDbContext> dbContextOptions,
        IOptions<PostgreSqlOptions> options)
        : base(dbContextOptions)
    {
        this.options = options.Value;
    }

    /// <summary>
    /// Gets the outbox entries DbSet.
    /// </summary>
    public DbSet<OutboxEntry> OutboxEntries => Set<OutboxEntry>();

    /// <summary>
    /// Gets the lease entities DbSet.
    /// </summary>
    public DbSet<LeaseEntity> Leases => Set<LeaseEntity>();

    /// <summary>
    /// Gets the sequence counters DbSet.
    /// </summary>
    public DbSet<SequenceCounter> SequenceCounters => Set<SequenceCounter>();

    /// <inheritdoc/>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // OutboxAttempt is stored as JSONB, not as a separate entity
        modelBuilder.Ignore<OutboxAttempt>();

        ConfigureOutboxEntry(modelBuilder);
        ConfigureLeaseEntity(modelBuilder);
        ConfigureSequenceCounter(modelBuilder);
    }

    private void ConfigureOutboxEntry(ModelBuilder modelBuilder)
    {
        var entity = modelBuilder.Entity<OutboxEntry>();

        // Table name from options
        entity.ToTable(options.TableName);

        // Primary key - UUID with value converter for object? type
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id)
            .HasColumnName("id")
            .HasColumnType("uuid")
            .HasDefaultValueSql("gen_random_uuid()")
            .HasConversion(
                v => v == null ? Guid.Empty : (Guid)v,
                v => (object?)v);

        // Sequence - BIGINT GENERATED BY DEFAULT AS IDENTITY
        // Using BY DEFAULT allows explicit values while still auto-generating when not provided
        entity.Property(e => e.Sequence)
            .HasColumnName("sequence")
            .HasColumnType("bigint")
            .UseIdentityByDefaultColumn();

        // String properties
        entity.Property(e => e.ProviderId)
            .HasColumnName("provider_id")
            .HasMaxLength(100)
            .IsRequired();

        entity.Property(e => e.RegistrationKey)
            .HasColumnName("registration_key")
            .HasMaxLength(200)
            .IsRequired();

        entity.Property(e => e.GroupKey)
            .HasColumnName("group_key")
            .HasMaxLength(500)
            .IsRequired();

        entity.Property(e => e.CorrelationId)
            .HasColumnName("correlation_id")
            .HasMaxLength(200);

        entity.Property(e => e.LatestError)
            .HasColumnName("latest_error")
            .HasColumnType("text");

        // Status - stored as string
        entity.Property(e => e.Status)
            .HasColumnName("status")
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

        // Retry count
        entity.Property(e => e.RetryCount)
            .HasColumnName("retry_count")
            .HasDefaultValue(0);

        // DateTime properties - UTC timestamps
        entity.Property(e => e.EnqueuedAt)
            .HasColumnName("enqueued_at")
            .HasColumnType("timestamp with time zone")
            .IsRequired();

        entity.Property(e => e.CompletedAt)
            .HasColumnName("completed_at")
            .HasColumnType("timestamp with time zone");

        entity.Property(e => e.LastAttemptedAt)
            .HasColumnName("last_attempted_at")
            .HasColumnType("timestamp with time zone");

        // Payload - BYTEA
        entity.Property(e => e.Payload)
            .HasColumnName("payload")
            .HasColumnType("bytea")
            .IsRequired();

        // Properties - JSONB
        entity.Property(e => e.Properties)
            .HasColumnName("properties")
            .HasColumnType("jsonb")
            .HasConversion(
                v => JsonSerializer.Serialize(v, JsonSerializerOptions.Default),
                v => JsonSerializer.Deserialize<Dictionary<string, string>>(v, JsonSerializerOptions.Default) ?? new Dictionary<string, string>());

        // Attempts - JSONB array (using backing field)
        entity.Property<List<OutboxAttempt>>("attempts")
            .HasColumnName("attempts")
            .HasColumnType("jsonb")
            .HasConversion(
                v => JsonSerializer.Serialize(v, JsonSerializerOptions.Default),
                v => JsonSerializer.Deserialize<List<OutboxAttempt>>(v, JsonSerializerOptions.Default) ?? new List<OutboxAttempt>(),
                new ValueComparer<List<OutboxAttempt>>(
                    (c1, c2) => c1 != null && c2 != null && c1.SequenceEqual(c2),
                    c => c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),
                    c => c.ToList()));

        // Indexes
        entity.HasIndex(e => new { e.GroupKey, e.Sequence })
            .IsUnique()
            .HasDatabaseName("ix_outbox_group_key_sequence");

        entity.HasIndex(e => new { e.Status, e.GroupKey })
            .HasDatabaseName("ix_outbox_status_group_key");

        entity.HasIndex(e => e.CompletedAt)
            .HasDatabaseName("ix_outbox_completed_at");
    }

    private void ConfigureLeaseEntity(ModelBuilder modelBuilder)
    {
        var entity = modelBuilder.Entity<LeaseEntity>();

        // Table name from options
        entity.ToTable(options.LeaseTableName);

        // Primary key
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id)
            .HasColumnName("id")
            .HasMaxLength(50);

        // Worker ID
        entity.Property(e => e.WorkerId)
            .HasColumnName("worker_id")
            .HasMaxLength(200);

        // Lease expiry - UTC timestamp
        entity.Property(e => e.LeaseUntil)
            .HasColumnName("lease_until")
            .HasColumnType("timestamp with time zone")
            .IsRequired();
    }

    private void ConfigureSequenceCounter(ModelBuilder modelBuilder)
    {
        var entity = modelBuilder.Entity<SequenceCounter>();

        // Table name from options
        entity.ToTable(options.SequenceTableName);

        // Primary key - GroupKey
        entity.HasKey(e => e.GroupKey);
        entity.Property(e => e.GroupKey)
            .HasColumnName("group_key")
            .HasMaxLength(500);

        // Sequence counter
        entity.Property(e => e.Sequence)
            .HasColumnName("sequence")
            .HasColumnType("bigint")
            .HasDefaultValue(0L);
    }
}
