global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: building-sentinel
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: /metrics

  - job_name: inventory-snapshot
    static_configs:
      - targets: ["host.docker.internal:5001"]
    metrics_path: /metrics

  - job_name: batch-consumer
    static_configs:
      - targets: ["host.docker.internal:5002"]
    metrics_path: /metrics
